# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_semi_analyticalwrap')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_semi_analyticalwrap')
    _semi_analyticalwrap = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_semi_analyticalwrap', [dirname(__file__)])
        except ImportError:
            import _semi_analyticalwrap
            return _semi_analyticalwrap
        try:
            _mod = imp.load_module('_semi_analyticalwrap', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _semi_analyticalwrap = swig_import_helper()
    del swig_import_helper
else:
    import _semi_analyticalwrap
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def SA_wrap_arr(y, x, phi_Y, dphi_Y, phi_L, dphi_L, E, same, xk, wk, n, Area_i):
    return _semi_analyticalwrap.SA_wrap_arr(y, x, phi_Y, dphi_Y, phi_L, dphi_L, E, same, xk, wk, n, Area_i)
SA_wrap_arr = _semi_analyticalwrap.SA_wrap_arr

def P2P_c(MY, dMY, ML, dML, triangle, tri, k, xi, yi, zi, s_xj, s_yj, s_zj, xt, yt, zt, m, mx, my, mz, mclean, targets, Area, xk, wk, E, threshold, eps, w0, aux, n, Area_i):
    return _semi_analyticalwrap.P2P_c(MY, dMY, ML, dML, triangle, tri, k, xi, yi, zi, s_xj, s_yj, s_zj, xt, yt, zt, m, mx, my, mz, mclean, targets, Area, xk, wk, E, threshold, eps, w0, aux, n, Area_i)
P2P_c = _semi_analyticalwrap.P2P_c
# This file is compatible with both classic and new-style classes.


